### PR TITLE
Update README to reflect new repository

### PR DESCRIPTION
**Pull request by stevendanna**

### CODE REVIEW

**Comment by stevendanna** [comment]
cc @chef/lob @chef/chef-visual-interaction

**Comment by mmzyk** [comment]
@ssd Perhaps we should put the chef server version # at the time of cut over? It says work on older versions should go here, but that assumes I know the version when we cut over.

**Comment by stevendanna** [comment]
@mmzyk Good point.  I don't think the exact version is actually desirable here as it might give the long impression.  The only thing that should use this repository is if we have items that we need to backport to Chef Server 11.

**Comment by mmzyk** [comment]
@ssd That's fine, just so long as that's clear. If we can build all the 12 versions from the chef-server repo then it makes sense to use the 11/12 changes as the cut over point.

**Comment by stevendanna** [comment]
@mmzyk What do you think of the update?

**Comment by mmzyk** [comment]
:+1: Love it.

**Pull request merged**
